### ISSUE TITLE
Installation is broken for both --full and normal installs

### ISSUE THREAD

**Issue by IMS-Global** [wdjungst/create-repack-app#6]
Brennicks-MacBook-Air:Projects biosci$ create-repack-app vertical-coop-app --full
Welcome To Create Repack App.

? Do you have create-react-app installed and globally available? Yes

Writing Server Code...
Writing Client Code...

Please Wait, This Could Take A Few Minutes...

? Rails server port 3001

Performing A Full Install. (Rails, React, React Router, Redux, Devise, Devise Token Auth, Authentication Components)

Please Wait, This Could Take A Few Minutes...

(node:22043) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, open 'vertical-coop-app/client/package.json'
(node:22043) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Project Built Successfully!

GETTING STARTED:
cd vertical-coop-app
rails s -p 3001
cd client
yarn start or npm run start

PRODUCTION:
If deploying to heroku:
heroku buildpacks:clear
heroku buildpacks:set heroku/nodejs
heroku buildpacks:add heroku/ruby --index 2

If not deploying to heroku:
From root folder: yarn build && yarn deploy

-------------------------------------------------------------------------------------------
The following json package file does not get created: /client/package.json

**Comment by wdjungst** [comment]
https://github.com/npm/registry/issues/255 this is because create-react-app is broken because some packages are missing from npm
